<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }} - Kwati AI</title>
    <style>
        @page {
            margin: 50px 30px;
        }
        
        body {
            font-family: 'Arial', 'Helvetica', sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 0;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 15px;
            border-bottom: 2px solid #3498db;
        }
        
        .title {
            font-size: 28px;
            font-weight: bold;
            color: #2c3e50;
            margin-bottom: 10px;
        }
        
        .subtitle {
            font-size: 14px;
            color: #7f8c8d;
            margin-bottom: 5px;
        }
        
        .metadata {
            font-size: 11px;
            color: #95a5a6;
            margin-top: 20px;
        }
        
        .content {
            margin-top: 20px;
        }
        
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            height: 30px;
            text-align: center;
            font-size: 10px;
            color: #95a5a6;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
        
        .page-number:before {
            content: "Page " counter(page);
        }
        
        /* Enhance markdown styling */
        h1 {
            font-size: 22px;
            font-weight: bold;
            margin-top: 25px;
            margin-bottom: 15px;
            color: #2c3e50;
            border-bottom: 1px solid #eee;
            padding-bottom: 5px;
        }
        
        h2 {
            font-size: 18px;
            font-weight: bold;
            margin-top: 20px;
            margin-bottom: 12px;
            color: #34495e;
        }
        
        h3 {
            font-size: 16px;
            font-weight: bold;
            margin-top: 18px;
            margin-bottom: 10px;
            color: #7f8c8d;
        }
        
        h4 {
            font-size: 14px;
            font-weight: bold;
            margin-top: 16px;
            margin-bottom: 8px;
            color: #95a5a6;
        }
        
        p {
            margin-bottom: 12px;
            text-align: justify;
        }
        
        ul, ol {
            margin-left: 25px;
            margin-bottom: 15px;
        }
        
        li {
            margin-bottom: 6px;
        }
        
        strong {
            font-weight: bold;
            color: #2c3e50;
        }
        
        em {
            font-style: italic;
        }
        
        blockquote {
            border-left: 3px solid #3498db;
            margin: 15px 0;
            padding: 10px 15px;
            background-color: #f8f9fa;
            font-style: italic;
        }
        
        code {
            background-color: #f8f9fa;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 0.9em;
        }
        
        pre {
            background-color: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
            overflow-x: auto;
            font-family: 'Courier New', monospace;
            font-size: 0.9em;
            margin: 15px 0;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        
        .section-break {
            page-break-before: always;
        }
        
        .no-break {
            page-break-inside: avoid;
        }
    </style>
</head>
<body>
    @if($includeHeader)
    <div class="header">
        <div class="title">{{ $title }}</div>
        <div class="subtitle">Generated by Kwati AI</div>
        <div class="metadata">
            Document Type: {{ ucfirst($documentType) }} | 
            Generated: {{ $generatedAt }}
        </div>
    </div>
    @endif
    
    <div class="content">
        {!! $content !!}
    </div>
    
    @if($includePageNumbers)
    <div class="footer">
        <div class="page-number"></div>
        <div>Generated by Kwati AI - Document ID: {{ Str::random(8) }}</div>
    </div>
    @endif
</body>
</html>