<?php
// database/migrations/2025_12_03_245201_seed_agent_plans.php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $plans = [
            [
                'id' => '019a9ded-f5a3-7197-b715-9b60de30ceae',
                'name' => 'Free',
                'slug' => 'free',
                'description' => 'Get started with 1 site and basic AI agent',
                'type' => 'mixed',
                'monthly_price' => 0.00,
                'yearly_price' => 0.00,
                'max_sites' => 1,
                'max_agents_per_site' => 1,
                'max_total_agents' => 1,
                'max_monthly_conversations' => 100,
                'max_daily_conversations' => 10,
                'max_monthly_messages' => 1000,
                'knowledge_base_size_mb' => 10,
                'max_file_uploads' => 5,
                'custom_domains_allowed' => false,
                'white_label_allowed' => false,
                'api_access' => false,
                'webhook_support' => false,
                'advanced_analytics' => false,
                'priority_support' => false,
                'custom_branding' => false,
                'sso_integration' => false,
                'features' => json_encode(['basic_widget', 'chat', 'faq_knowledge_base', 'email_notifications']),
                'limits' => json_encode(['max_file_size' => 5, 'max_kb_entries' => 50]),
                'is_active' => true,
                'display_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '019a9ded-f5a4-7197-b715-9b60de30ceae',
                'name' => 'Starter',
                'slug' => 'starter',
                'description' => 'Perfect for small businesses',
                'type' => 'mixed',
                'monthly_price' => 19.99,
                'yearly_price' => 199.99,
                'max_sites' => 3,
                'max_agents_per_site' => 3,
                'max_total_agents' => 5,
                'max_monthly_conversations' => 1000,
                'max_daily_conversations' => 50,
                'max_monthly_messages' => 10000,
                'knowledge_base_size_mb' => 100,
                'max_file_uploads' => 50,
                'custom_domains_allowed' => true,
                'white_label_allowed' => false,
                'api_access' => true,
                'webhook_support' => true,
                'advanced_analytics' => true,
                'priority_support' => false,
                'custom_branding' => true,
                'sso_integration' => false,
                'features' => json_encode(['advanced_widget', 'chat', 'knowledge_base', 'web_search', 'file_upload', 'analytics', 'api_access']),
                'limits' => json_encode(['max_file_size' => 10, 'max_kb_entries' => 200]),
                'is_active' => true,
                'display_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '019a9ded-f5a5-7197-b715-9b60de30ceae',
                'name' => 'Business',
                'slug' => 'business',
                'description' => 'For growing businesses with multiple sites',
                'type' => 'mixed',
                'monthly_price' => 49.99,
                'yearly_price' => 499.99,
                'max_sites' => 10,
                'max_agents_per_site' => 5,
                'max_total_agents' => 20,
                'max_monthly_conversations' => 5000,
                'max_daily_conversations' => 200,
                'max_monthly_messages' => 50000,
                'knowledge_base_size_mb' => 500,
                'max_file_uploads' => 200,
                'custom_domains_allowed' => true,
                'white_label_allowed' => true,
                'api_access' => true,
                'webhook_support' => true,
                'advanced_analytics' => true,
                'priority_support' => true,
                'custom_branding' => true,
                'sso_integration' => true,
                'features' => json_encode(['premium_widget', 'voice_chat', 'advanced_knowledge_base', 'web_search', 'file_upload', 'advanced_analytics', 'custom_tools', 'priority_support']),
                'limits' => json_encode(['max_file_size' => 25, 'max_kb_entries' => 1000]),
                'is_active' => true,
                'display_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '019a9ded-f5a6-7197-b715-9b60de30ceae',
                'name' => 'Enterprise',
                'slug' => 'enterprise',
                'description' => 'Unlimited sites and agents with dedicated support',
                'type' => 'mixed',
                'monthly_price' => 199.99,
                'yearly_price' => 1999.99,
                'max_sites' => null,
                'max_agents_per_site' => null,
                'max_total_agents' => null,
                'max_monthly_conversations' => null,
                'max_daily_conversations' => null,
                'max_monthly_messages' => null,
                'knowledge_base_size_mb' => null,
                'max_file_uploads' => null,
                'custom_domains_allowed' => true,
                'white_label_allowed' => true,
                'api_access' => true,
                'webhook_support' => true,
                'advanced_analytics' => true,
                'priority_support' => true,
                'custom_branding' => true,
                'sso_integration' => true,
                'features' => json_encode(['unlimited_widgets', 'voice_chat', 'unlimited_knowledge_base', 'web_search', 'file_upload', 'enterprise_analytics', 'custom_tools', 'dedicated_support', 'sso', 'custom_integrations']),
                'limits' => json_encode(['max_file_size' => 100, 'max_kb_entries' => null]),
                'is_active' => true,
                'display_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($plans as $plan) {
            DB::table('agent_plans')->insert($plan);
        }
    }

    public function down(): void
    {
        DB::table('agent_plans')->whereIn('id', [
            '019a9ded-f5a3-7197-b715-9b60de30ceae',
            '019a9ded-f5a4-7197-b715-9b60de30ceae',
            '019a9ded-f5a5-7197-b715-9b60de30ceae',
            '019a9ded-f5a6-7197-b715-9b60de30ceae',
        ])->delete();
    }
};
